name: Java Spring Boot App CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to dockerhub
        env:
          - DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          - DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        uses: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        uses: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-spring-boot-app:${{ steps.commit_sha.outputs.SHA }} .
      - name: Push docker image to dockerhub
        uses: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-spring-boot-app:${{ steps.commit_sha.outputs.SHA }}