name: Java Spring Boot App CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    env:
      - DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      - DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to dockerhub
        run: docker login -u ${{ DOCKERHUB_USERNAME }} -p ${{ DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t ${{ DOCKERHUB_USERNAME }}/hello-world-spring-boot-app:${{ steps.commit_sha.outputs.SHA }} .
      - name: Push docker image to dockerhub
        run: docker push ${{ DOCKERHUB_USERNAME }}/hello-world-spring-boot-app:${{ steps.commit_sha.outputs.SHA }}