name: CICD Pipeline/Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  ci-build-and-push-docker-image:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to dockerhub
        run: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - name: Build docker image
        run: docker build -t $DOCKERHUB_USERNAME/hello-world-spring-boot-app:${{ github.sha }} .
      - name: Push docker image to dockerhub
        run: docker push $DOCKERHUB_USERNAME/hello-world-spring-boot-app:${{ github.sha }}
  cd-deploy-container-to-ec2:
    runs-on: self-hosted  # Note: you can replace "self-hosted" with the label of your self-hosted runner
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    needs: ci-build-and-push-docker-image
    steps:
      - name: Stop running docker containers
        run: |
          if [ -n "$(docker ps -q --filter status=running)" ]; then
            docker rm -f $(docker ps -q --filter status=running)
          fi
      - name: Delete existing docker images
        run: |
          if [ -n "$(docker images -q)" ]; then
            docker rmi $(docker images -q)
          fi
      - name: Pull docker image
        run: docker pull $DOCKERHUB_USERNAME/hello-world-spring-boot-app:${{ github.sha }}
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name spring-boot-app $DOCKERHUB_USERNAME/hello-world-spring-boot-app:${{ github.sha }} 
      - name: Test the hello-world endpoint
        run: sleep 20 && curl -X GET localhost:8080/api/hello-world/
